name: sync2gitee(list.org)

on:
  push:
  workflow_dispatch:
  schedule:
    # UTC 17:30 -> CST (China) 1:30 see https://datetime360.com/cn/utc-cst-china-time/
    - cron: '30 17 * * *'

jobs:
  run:
    name: Sync GitHub to Gitee(list)
    runs-on: ubuntu-latest
    steps:

      - name: Get repo and time
        id: info
        uses: actions/github-script@v3.1
        with:
          result-encoding: string
          script: |
            core.setOutput('time', new Date(Date.now()).toISOString().replace(/[^0-9]/g, ""));
            core.setOutput('key', `${context.repo.owner}-${context.repo.repo}`);

      - name: Cache src repos
        uses: actions/cache@v2.1.3
        id: cache
        with:
          path: ${{ github.workspace }}/hub-mirror-cache
          key: '${{ runner.os }}-${{ steps.info.outputs.key }}-list-cache-${{ steps.info.outputs.time }}'
          restore-keys: ${{ runner.os }}-${{ steps.info.outputs.key }}-list-

      - name: Generate repo list
        id: repo
        uses: yi-Xu-0100/repo-list-generator@v1.0.0
        with:
          user: coolephp

      - name: Mirror hub with cache and list
        uses: Yikun/hub-mirror-action@v0.13
        with:
          src: github/coolephp
          dst: gitee/coolephp
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          black_list: 'jetbrains-agent'
          static_list: '${{ steps.repo.outputs.repoList }}'
          cache_path: /github/workspace/hub-mirror-cache
          account_type: org
          force_update: true

      - name: Print cache path
        run: |
          ls -la ${{ github.workspace }}/hub-mirror-cache